import type { ServiceId, ServiceMeta } from "@/lib/services/types";

export const SERVICE_META: Record<ServiceId, ServiceMeta> = {
  meatguy: {
    id: "meatguy",
    name: "The Meat Guy",
    kind: "data",
    homepage: "https://www.themeatguy.jp",
    deliveryArea: "Ships nationwide within Japan",
    deliveryFee: "¥980–1,750 depending on region, free over ¥10,000",
  },
  tengunaturalfoods: {
    id: "tengunaturalfoods",
    name: "Tengu Natural Foods",
    kind: "data",
    homepage: "https://store.alishan.jp",
    deliveryArea: "Ships nationwide within Japan",
    deliveryFee: "¥660–1,100 depending on region, free over ¥5,250",
  },
  halalfoodjp: {
    id: "halalfoodjp",
    name: "Halal Food Japan",
    kind: "data",
    homepage: "https://halalfoodjp.com",
    deliveryArea: "Ships nationwide within Japan",
    deliveryFee: "Fee not published; free over ¥10,000 (¥20,000 for Hokkaido/Okinawa)",
  },
  nationalazabu: {
    id: "nationalazabu",
    name: "National Azabu",
    kind: "data",
    homepage: "https://national-azabu.net",
    deliveryArea: "Ships nationwide within Japan",
    deliveryFee: "¥550, free over ¥5,000",
  },
  kaldi: {
    id: "kaldi",
    name: "Kaldi Coffee Farm",
    kind: "data",
    homepage: "https://www.kaldi.co.jp",
    deliveryArea: "Ships nationwide within Japan",
    deliveryFee: "¥880, free over ¥7,000 (room-temperature items)",
  },
  asiasuperstore: {
    id: "asiasuperstore",
    name: "Asia Superstore",
    kind: "data",
    homepage: "https://asia-superstore.com/en/shopin",
    deliveryArea: "Ships nationwide within Japan",
    deliveryFee: "¥762–4,612 by weight/region (+¥980 frozen surcharge); no free-shipping threshold",
  },
  iherb: {
    id: "iherb",
    name: "iHerb",
    kind: "link-out",
    homepage: "https://jp.iherb.com",
    deliveryArea: "Ships nationwide within Japan",
    deliveryFee: "¥500, free over ¥6,000",
  },
  amazonfresh: {
    id: "amazonfresh",
    name: "Amazon Fresh",
    kind: "link-out",
    homepage: "https://www.amazon.co.jp",
    deliveryArea: "Tokyo, Kanagawa, Chiba, and parts of Saitama only",
    deliveryFee: "¥490 (Prime) / ¥690, free over ¥10,000",
  },
  amazonjp: {
    id: "amazonjp",
    name: "Amazon.co.jp",
    kind: "link-out",
    homepage: "https://www.amazon.co.jp",
    deliveryArea: "Ships nationwide within Japan",
    deliveryFee: "Free over ¥3,500 (¥460+ otherwise); free always with Prime",
  },
  ubereats: {
    id: "ubereats",
    name: "Uber Eats",
    kind: "link-out",
    homepage: "https://www.ubereats.com/jp",
    deliveryArea: "Varies by store/area availability",
    deliveryFee: "Varies by store/area",
  },
};
